##########
# GLOBAL #
##########

### resources
# ui
globalvar resourceNames = [
	"minerals",
	"vespene gas",
	"gold",
	"lumber",
	"stone",
	"food"
]

globalvar resourceIcons = [

]

globalvar resourceColors = [
	Color.SKY_BLUE,
	Color.LIME_GREEN,
	Color.YELLOW,
	Color.ORANGE,
	Color.GRAY,
	Color.ROSE
]

# rarities
globalvar rarities = []

### overseer
globalvar overseerPos =
globalvar overseerColor =
globalvar 